
--ABY ZNALEZC TOP6 KSI•ØEK TRZEBA WYPISAC TOP 6 OCEN A POTEM W P TLI DO KAØDEJ OCENY ODNALEè∆ KSI•ØK  Z WIDOKU ALLBOOKS

SELECT TOP 6 AVG(ocena) as Ocenaårednia,id_ks
FROM Oceny
GROUP BY id_ks
ORDER BY id_ks DESC

SELECT * FROM ALLBOOKS WHERE id='szukane id'