--TUTAJ JEST SELECT DO SZUKANIA KSI¥¯EK PO KATEGORII, W MIEJSCE 'LITERATURA FAKTU' MO¯ECIE WSTAWIÆ ZMIENN¥ Z NAZW¥ KATEGORII LUB DLA KA¯DEJ KATEGORII RÊCZNIE TO ZMIENIÆ

Select DISTINCT * from ALLBOOKS WHERE Kategoria = 'Literatura faktu'

